FROM apache/spark:3.5.4-java17-python3

USER root

# python3 위치 확인 후 심볼릭 링크 (python 명령어로 사용할 수 있도록 설정)
RUN ln -sf $(which python3) /usr/bin/python

# pandas 설치
RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir pandas==2.2.3 && \
    python3 -m pip install --no-cache-dir elasticsearch==8.17.0

# Elasticsearch Spark Connector JAR 다운로드
RUN mkdir -p /opt/spark/jars && \
    curl -L -o /opt/spark/jars/elasticsearch-spark-30_2.12-8.17.0.jar \
    https://repo1.maven.org/maven2/org/elasticsearch/elasticsearch-spark-30_2.12/8.17.0/elasticsearch-spark-30_2.12-8.17.0.jar && \
    chmod 644 /opt/spark/jars/elasticsearch-spark-30_2.12-8.17.0.jar

# Spark --packages 사용 시 Ivy가 의존성 파일을 저장할 디렉터리 생성
RUN mkdir -p /home/spark/.ivy2/cache /home/spark/.ivy2/jars && \
    chown -R spark:spark /home/spark/.ivy2

USER spark

