


ALTER TABLE users 
ADD COLUMN profile_picture VARCHAR(100) NOT NULL;

ALTER TABLE users
MODIFY COLUMN email VARCHAR(320);

ALTER TABLE posts
ADD COLUMN title VARCHAR(255) NOT NULL;

ALTER TABLE posts
MODIFY COLUMN contents LONGTEXT;