FROM apache/spark:3.5.4-java17-python3

USER root

# python3 위치 확인 후 심볼릭 링크 (python 명령어로 사용할 수 있도록 설정)
RUN ln -sf $(which python3) /usr/bin/python

# pandas 설치
RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir pandas==2.2.3

USER spark

